#!/bin/bash

SCRIPT_FOLDER="${HOME}/configs/autoscripts"
SCRIPT_FILE="$SCRIPT_FOLDER/$1"
EDITOR_CMD="emacsclient -t"

if [[ -f $SCRIPT_FILE ]]; then
  $EDITOR_CMD $SCRIPT_FILE
else
  echo '#!/bin/bash' > $SCRIPT_FILE
  chmod +x $SCRIPT_FILE
  $EDITOR_CMD $SCRIPT_FILE
fi

