# If you come from bash you might have to change your $PATH.
export PATH=$HOME.local/bin:/usr/local/bin:$PATH

export TERM="xterm-256color"

# Path to your oh-my-zsh installation.
export ZSH=/usr/share/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="classyTouch"
ZSH_THEME="../../zsh-theme-powerlevel9k/powerlevel9k"
POWERLEVEL9K_MODE='nerdfont-complete'
# POWERLEVEL9K_MODE='awesome-fontconfig'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir rbenv pyenv virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs os_icon)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0C6'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0c7'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$'\uE0C4'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$'\uE0c5'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{yellow}%K{black}%} \uf120 %b%f%k%F{black}%}\ue0c4 %{%f%}"
POWERLEVEL9K_LINUX_ICON=$'\uF300'

POWERLEVEL9K_VIRTUALENV_FOREGROUND='232'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='061'
POWERLEVEL9K_PYENV_FOREGROUND='232'
POWERLEVEL9K_PYENV_BACKGROUND='purple'
POWERLEVEL9K_OS_ICON_FOREGROUND='147'
POWERLEVEL9K_OS_ICON_BACKGROUND='027'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='7'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='3'
[ -n "$PS1" ] && sh ~/.vim-spectr/shell/vimspectrgrey-dark
# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLd="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git sudo)

source $ZSH/oh-my-zsh.sh

# User configuration

# Preferred editor for local and remote sessions
# Emacs
export EDITOR="emacsclient -t"
export ALTERNATE_EDITOR=""
export VISUAL="emacsclient -c"         # $VISUAL opens in GUI with non-daemon as alternate
alias e="emacsclient -c"                      # used to be "emacs -nw"
alias et="emacsclient -t"                      # used to be "emacs -nw"
alias restart-emacs="systemctl restart emacs"

# ls is so ANNOYING
alias ls="ls --color=never"
# FASD
eval "$(fasd --init auto)"
alias ef='f -e "emacsclient -t"' # quick opening files with emacs

# Compilation flags
export ARCHFLAGS="-arch x86_64"

if ! pgrep -u "$USER" ssh-agent > /dev/null; then
    ssh-agent > ~/.ssh-agent-thing
fi
if [[ "$SSH_AGENT_PID" == "" ]]; then
    eval "$(<~/.ssh-agent-thing)" > /dev/null
fi

# Aliases
alias cc_args="python ~/_configs/scripts/cc_args.py"

# Virtual Env stuff
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Documents/VENV_PROJECTS
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv
export VIRTUALENVWRAPPER_SCRIPT=/usr/bin/virtualenvwrapper.sh
source /usr/bin/virtualenvwrapper_lazy.sh
