export TERM="xterm-256color"

# Set up the prompt
autoload -Uz promptinit
promptinit
prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

export EDITOR="emacsclient -t"
export ALTERNATE_EDITOR="emacs"
export VISUAL="emacsclient -c"         # $VISUAL opens in GUI with non-daemon as alternate
alias e="emacsclient -c"                      # used to be "emacs -nw"
alias et="emacsclient -t"                      # used to be "emacs -nw"

eval "$(fasd --init posix-hook posix-alias)"
alias fcd="fasd_cd -id"

# Virtual Env stuff
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Documents/VENV_PROJECTS
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv
export VIRTUALENVWRAPPER_SCRIPT=/usr/local/bin/virtualenvwrapper.sh
source /usr/local/bin/virtualenvwrapper_lazy.sh

export PIPENV_VENV_IN_PROJECT=1

LFCD=~/configs/config/lf/lfcd.sh
if [ -f "$LFCD" ]; then
    source "$LFCD"
fi

if command -v pyenv 1>/dev/null 2>&1; then
    eval "$(pyenv init -)"
fi

POWERLEVEL9K_MODE='nerdfont-complete'

POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir pyenv virtualenv vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time root_indicator background_jobs)
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=$'\uE0C6'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=$'\uE0c7'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=$'\uE0C4'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=$'\uE0c5'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%{%B%F{yellow}%K{black}%} \uf120 %b%f%k%F{black}%}\ue0c4 %{%f%}"
POWERLEVEL9K_LINUX_ICON=$'\uF300'

POWERLEVEL9K_VIRTUALENV_FOREGROUND='232'
POWERLEVEL9K_VIRTUALENV_BACKGROUND='061'
POWERLEVEL9K_PYENV_FOREGROUND='232'
POWERLEVEL9K_PYENV_BACKGROUND='purple'
POWERLEVEL9K_OS_ICON_FOREGROUND='147'
POWERLEVEL9K_OS_ICON_BACKGROUND='027'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='7'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='3'

source  ~/powerlevel9k/powerlevel9k.zsh-theme
